spring.application.name=AWS Assignment 2
server.port=80

aws.region=us-east-1
aws.bucket-name=A2-music-images
aws.json-file=2026a2_songs.json
aws.use-local=true
aws.local-endpoint=http://localhost:8000