spring.application.name=AWS Assignment 2
server.port=8080

aws.region=us-east-1
aws.bucket-name=A2-music-images
aws.json-file=2026a2_songs.json
aws.use-local=true
aws.seed-data=true
aws.local-endpoint=http://localhost:8000
aws.accessKeyId=${AWS_ACCESS_KEY_ID:dummy}
aws.secretKey=${AWS_SECRET_ACCESS_KEY:dummy}
